#들여쓰기 기준

services:
  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/cert.pem:/etc/nginx/cert/cert.pem
      - ./cert/key.pem:/etc/nginx/cert/key.pem
    ports:
      - 80:80
      - 443:443
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - react_app_1
      - react_app_2
      - nestjs_api
    networks:
      - koreanmarket-network

  nestjs_api:
    build:
      dockerfile: Dockerfile
      context: Backend
      target: development
    volumes:
      - ./Backend:/usr/src/app
    env_file:
      - ./Backend/.env
    command: npm run start:dev
    ports:
      - 8000:8000
    networks:
      - koreanmarket-network


  react_app_1:
    container_name: react_app_1
    build:
      dockerfile: Dockerfile
      context: Front
      target: development
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - koreanmarket-network

  react_app_2:
    container_name: react_app_2
    build:
      dockerfile: Dockerfile
      context: Front
      target: development
    command: npm run start
    ports:
      - 3001:3000
    networks:
      - koreanmarket-network


networks:
  koreanmarket-network:
